name: lab_7
description: "Lab 7 + Lab 8 (Constants and Localization Integration)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
   sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  json_annotation: ^4.7.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
   sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^5.13.0
  retrofit_generator: ^4.0.3+1
  build_runner: ^2.2.1
  json_serializable: ^6.3.1

flutter:
   uses-material-design: true
   
   assets:
    - assets/translations/
